#customhost = "employee.coghw13fheqo.us-east-2.rds.amazonaws.com"
#customuser = "intellipaat"
#custompass = "intellipaat123"
#customdb = "employee"
#custombucket = "addemployee"
#customregion = "us-east-2"

customhost = "employee.cuvxoblh4luj.us-east-2.rds.amazonaws.com"
customuser = "swapnil"
custompass = "swapnil22"
customdb = "employee"
custombucket = "employeess"
customregion = "us-east-2"
